Repository team-devOops/Chal-Chal-Server, pull requests merged in 2023-01, with the labels that each got.

#14 Slack 오류 알림 개발
  build.gradle
  src/main/resources/application.yml
  src/main/resources/config-template/slack-config.yml
  src/main/resources/logback-slack.xml
  src/main/resources/logback.xml
Labels: enhancement

#15 To do 작성기능
  src/main/java/com/chalchal/chalchalsever/domain/BaseDomain.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/entity/User.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/entity/UserTokenInfo.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/service/UserAuthServiceImpl.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/service/UserServiceImpl.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/controller/TodoController.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/dto/TodoListResponse.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/dto/TodoListSaveRequest.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/dto/TodoListSaveResponse.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/dto/TodoListUpdateRequest.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/entity/TodoList.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/repository/TodoRepository.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/service/TodoService.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/service/TodoServiceImpl.java
  src/main/java/com/chalchal/chalchalsever/global/config/jpa/AuditorAwareImpl.java
  src/main/java/com/chalchal/chalchalsever/global/config/jpa/JpaAuditingConfig.java
  src/main/java/com/chalchal/chalchalsever/global/config/jwt/JwtUtils.java
  src/main/java/com/chalchal/chalchalsever/global/util/StringUtils.java
  src/main/resources/application.yml
  src/main/resources/banner.txt
  src/main/resources/config-template/database-config.yml
  src/test/java/com/chalchal/chalchalsever/StringUtilsTest.java
Labels: enhancement, question

#16 Entitiy data type 추가
  src/main/java/com/chalchal/chalchalsever/domain/auth/entity/User.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/entity/UserJoinAuth.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/entity/UserTokenInfo.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/entity/TodoList.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/service/TodoServiceImpl.java
  src/main/java/com/chalchal/chalchalsever/global/mail/entity/Mail.java
Labels: 🔨refactor

#17 할 일 group 개발
  src/main/java/com/chalchal/chalchalsever/domain/auth/controller/AuthController.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/dto/UserAuthRequest.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/dto/UserAuthResponse.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/entity/User.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/entity/UserJoinAuth.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/service/UserAuthServiceImpl.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/service/UserServiceImpl.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/controller/TodoTopicController.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/dto/TodoListSaveRequest.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/dto/TodoListSaveResponse.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/dto/TodoListUpdateRequest.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/dto/TodoTopicSaveRequest.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/dto/TodoTopicUpdateRequest.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/entity/TodoList.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/entity/TodoTopic.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/repository/TodoTopicRepository.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/service/TodoServiceImpl.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/service/TodoTopicService.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/service/TodoTopicServiceImpl.java
  src/main/java/com/chalchal/chalchalsever/global/dto/Flag.java
Labels: enhancement

#18 메일 인증 개발
  src/main/java/com/chalchal/chalchalsever/domain/auth/controller/AuthController.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/controller/AuthMailController.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/dto/LoginUserRequest.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/dto/UserAuthMailRequest.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/dto/UserAuthRequest.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/entity/MailAuthNum.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/entity/User.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/entity/UserJoinAuth.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/repository/UserAuthRepository.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/repository/UserRepository.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/service/UserAuthService.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/service/UserAuthServiceImpl.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/service/UserDetailsServiceImpl.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/service/UserServiceImpl.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/controller/TodoController.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/entity/TodoList.java
  src/main/java/com/chalchal/chalchalsever/global/config/security/WebSecurityConfig.java
  src/main/java/com/chalchal/chalchalsever/global/mail/dto/MailRequest.java
  src/main/java/com/chalchal/chalchalsever/global/mail/entity/MailAuthNum.java
  src/main/java/com/chalchal/chalchalsever/global/mail/service/MailService.java
  src/main/java/com/chalchal/chalchalsever/global/util/DateUtils.java
  src/main/java/com/chalchal/chalchalsever/global/util/RandomUtils.java
  src/test/java/com/chalchal/chalchalsever/StringUtilsTest.java
  src/test/java/com/chalchal/chalchalsever/auth/AuthTest.java
  src/test/java/com/chalchal/chalchalsever/utils/DateUtilsTest.java
  src/test/java/com/chalchal/chalchalsever/utils/RandomUtilsTest.java
  src/test/java/com/chalchal/chalchalsever/utils/StringUtilsTest.java
Labels: enhancement, 🔨refactor

#19 에러 공통처리 개발
  README.md
  src/main/java/com/chalchal/chalchalsever/domain/auth/controller/AuthController.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/controller/AuthMailController.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/entity/MailAuthNum.java
  src/main/java/com/chalchal/chalchalsever/domain/auth/service/UserServiceImpl.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/controller/TodoController.java
  src/main/java/com/chalchal/chalchalsever/domain/todo/controller/TodoTopicController.java
  src/main/java/com/chalchal/chalchalsever/global/dto/ErrorResponse.java
  src/main/java/com/chalchal/chalchalsever/global/dto/ResultResponse.java
  src/main/java/com/chalchal/chalchalsever/global/exception/BaseException.java
  src/main/java/com/chalchal/chalchalsever/global/exception/BaseExceptionHandler.java
  src/main/java/com/chalchal/chalchalsever/global/exception/ErrorCode.java
  src/main/java/com/chalchal/chalchalsever/global/mail/service/MailService.java
  src/test/java/com/chalchal/chalchalsever/SvcNoTest.java
  src/test/java/com/chalchal/chalchalsever/auth/AuthTest.java
Labels: documentation, 🔨refactor

#21 docs: Dockerfile 수정
  Dockerfile
Labels: chore

#22 도커 환경설정
  Dockerfile
Labels: documentation

#23 refactor: 인증번호 관련 유효성 검사 추가
  src/main/java/com/chalchal/chalchalserver/domain/auth/repository/UserAuthRepository.java
  src/main/java/com/chalchal/chalchalserver/domain/auth/service/UserAuthServiceImpl.java
  src/main/java/com/chalchal/chalchalserver/global/exception/ErrorCode.java
Labels: 🔨refactor

#24 프로젝트 리팩토링
  README.md
  build.gradle
  img.png
  src/main/java/com/chalchal/chalchalserver/domain/auth/controller/AuthController.java
  src/main/java/com/chalchal/chalchalserver/domain/auth/controller/AuthMailController.java
  src/main/java/com/chalchal/chalchalserver/domain/auth/controllerAdvice/AuthControllerAdvice.java
  src/main/java/com/chalchal/chalchalserver/domain/auth/dto/AuthNumCompareRequest.java
  src/main/java/com/chalchal/chalchalserver/domain/auth/dto/LoginUserRequest.java
  src/main/java/com/chalchal/chalchalserver/domain/auth/dto/UserAuthMailRequest.java
  src/main/java/com/chalchal/chalchalserver/domain/auth/dto/UserAuthRequest.java
  src/main/java/com/chalchal/chalchalserver/domain/auth/dto/UserRequest.java
  src/main/java/com/chalchal/chalchalserver/domain/auth/service/UserAuthServiceImpl.java
  src/main/java/com/chalchal/chalchalserver/domain/auth/service/UserDetailsServiceImpl.java
  src/main/java/com/chalchal/chalchalserver/domain/auth/service/UserServiceImpl.java
  src/main/java/com/chalchal/chalchalserver/domain/todo/controller/TodoController.java
  src/main/java/com/chalchal/chalchalserver/domain/todo/controller/TodoTopicController.java
  src/main/java/com/chalchal/chalchalserver/domain/todo/repository/TodoRepository.java
  src/main/java/com/chalchal/chalchalserver/domain/todo/service/TodoServiceImpl.java
  src/main/java/com/chalchal/chalchalserver/domain/todo/service/TodoTopicServiceImpl.java
  src/main/java/com/chalchal/chalchalserver/global/dto/ErrorResponse.java
  src/main/java/com/chalchal/chalchalserver/global/dto/Flag.java
  src/main/java/com/chalchal/chalchalserver/global/dto/ResultResponse.java
  src/main/java/com/chalchal/chalchalserver/global/exception/ErrorCode.java
  src/main/java/com/chalchal/chalchalserver/global/mail/service/MailService.java
Labels: documentation, 🔨refactor

#26 spring-retry 추가
  build.gradle
  src/main/java/com/chalchal/chalchalserver/auth/domain/UserJoinAuth.java
  src/main/java/com/chalchal/chalchalserver/auth/repository/UserAuthRepository.java
  src/main/java/com/chalchal/chalchalserver/auth/repository/UserRepository.java
  src/main/java/com/chalchal/chalchalserver/auth/repository/UserTokenInfoRepository.java
  src/main/java/com/chalchal/chalchalserver/auth/service/UserAuthService.java
  src/main/java/com/chalchal/chalchalserver/auth/service/UserDetailsServiceImpl.java
  src/main/java/com/chalchal/chalchalserver/auth/service/UserService.java
  src/main/java/com/chalchal/chalchalserver/auth/service/UserTokenInfoService.java
  src/main/java/com/chalchal/chalchalserver/global/config/retry/RetryConfig.java
  src/main/java/com/chalchal/chalchalserver/global/exception/BaseException.java
  src/main/java/com/chalchal/chalchalserver/global/exception/ErrorCode.java
  src/main/java/com/chalchal/chalchalserver/mail/service/MailService.java
  src/main/java/com/chalchal/chalchalserver/todo/repository/TodoRepository.java
  src/main/java/com/chalchal/chalchalserver/todo/repository/TodoTopicRepository.java
  src/main/java/com/chalchal/chalchalserver/todo/service/TodoService.java
  src/main/java/com/chalchal/chalchalserver/todo/service/TodoTopicService.java
Labels: enhancement, 🔨refactor

#28 배포스크립트 작성
  deploy.sh
Labels: deploy
